---
abstract: 'easily access options from higher up the command chain'
author:
  - 'Smithsonian Astrophysical Observatory'
build_requires:
  ExtUtils::MakeMaker: '6.36'
  Test::More: '0'
configure_requires:
  CPAN::Meta: '0'
  ExtUtils::MakeMaker: '6.36'
dynamic_config: '0'
generated_by: 'Module::Install version 1.14, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-Cmd-ChainedOptions
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Import::Into: '0'
  Module::Runtime: '0'
  Moo: '0'
  Moo::Role: '0'
  MooX::Cmd: '0'
  MooX::Options: '0'
  Package::Variant: '0'
  Scalar::Util: '0'
resources:
  license: http://opensource.org/licenses/gpl-3.0.html
  repository: https://bitbucket.org/djerius/moox-cmd-chainedoptions
version: '0.01'
